apiVersion: v1
kind: Service
metadata:
  name: kafka-zk
  labels:
    component: kafka
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - port: 9092
    name: server
  - port: 2181
    name: zkclient
  - port: 2888
    name: zkserver
  - port: 3888
    name: zkleader
  clusterIP: None
  selector:
    app: kafka-zk
    component: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-zk
  labels:
    app: kafka-zk
    component: kafka
spec:
  serviceName: kafka-zk
  selector:
    matchLabels:
      app: kafka-zk
      component: kafka
  replicas: 3
  podManagementPolicy: "Parallel"
  template:
    metadata:
      labels:
        app: kafka-zk
        component: kafka
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: kafka
        imagePullPolicy: IfNotPresent
        image: engapa/kafka:2.13-2.5.0
        resources:
          requests:
            memory: 512M
            cpu: 300m
          limits:
            memory: 512M
            cpu: 300m
        ports:
        - containerPort: 9092
          name: broker-port
        - containerPort: 2181
          name: zkclient
        - containerPort: 2888
          name: zkserver
        - containerPort: 3888
          name: zkleader
        env:
        - name:  KAFKA_REPLICAS
          value: "3"
        - name:  KAFKA_ZK_LOCAL
          value: "true"
        - name:  SERVER_zookeeper_connection_timeout_ms
          value: "300000"
#        livenessProbe:
#          exec:
#            command:
#            - kafka_server_status.sh
#          initialDelaySeconds: 60
#          timeoutSeconds: 60
#        readinessProbe:
#          exec:
#            command:
#            - kafka_server_status.sh
#          initialDelaySeconds: 60
#          timeoutSeconds: 60